// Basic C++ translation test.
// Test global printing functions.

caterwaul.clone('std seq continuation hlasm.cpp')(function () {
  console.log(caterwaul.hlasm.cpp({main: 'k10 kw [[. [.[a]z E tsI] [,w, k101ngk] /]]tZ tsI'}, {trace: false}))})();

// Generated by SDoc 
