// Basic C++ translation test.

caterwaul.clone('std seq continuation hlasm.cpp')(function () {
  console.log(caterwaul.hlasm.cpp({main: 'k10 kw [[. [.[a]z E tsI] [,w,] /]]Z tsI'}))})();

// Generated by SDoc 
