// Basic C++ translation test.
// This one uses the primality test.

caterwaul.clone('std seq continuation hlasm.cpp')(function () {
  console.log(caterwaul.hlasm.cpp({main: 'k2147483647 t [[..ctswl! [T+k] [Ks Ks d[,]z [e tsj] [T+K] /] /]]Z tsj'}))})();

// Generated by SDoc 
